// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD5N3PRYzoXbZ-XLhV8Z6UHKRoF4SzRadE',
    appId: '1:309848691890:web:86c8ce8fe5ea2bbabae5ab',
    messagingSenderId: '309848691890',
    projectId: 'fir-xflutterxauth-1b024',
    authDomain: 'fir-xflutterxauth-1b024.firebaseapp.com',
    storageBucket: 'fir-xflutterxauth-1b024.firebasestorage.app',
    measurementId: 'G-D5N1P3R661',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyByRphSuPDsM2dLF1Goi_T5Iz5np7lwtqI',
    appId: '1:309848691890:android:397b8ca9eac10210bae5ab',
    messagingSenderId: '309848691890',
    projectId: 'fir-xflutterxauth-1b024',
    storageBucket: 'fir-xflutterxauth-1b024.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCETA-Gtbh0rW7Z5nJbgxCDIOnkPQkb4Hc',
    appId: '1:309848691890:ios:41ae1d4d5e3d71a3bae5ab',
    messagingSenderId: '309848691890',
    projectId: 'fir-xflutterxauth-1b024',
    storageBucket: 'fir-xflutterxauth-1b024.firebasestorage.app',
    iosBundleId: 'com.iotecksolutions.flutterBoilerplateProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCETA-Gtbh0rW7Z5nJbgxCDIOnkPQkb4Hc',
    appId: '1:309848691890:ios:41ae1d4d5e3d71a3bae5ab',
    messagingSenderId: '309848691890',
    projectId: 'fir-xflutterxauth-1b024',
    storageBucket: 'fir-xflutterxauth-1b024.firebasestorage.app',
    iosBundleId: 'com.iotecksolutions.flutterBoilerplateProject',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD5N3PRYzoXbZ-XLhV8Z6UHKRoF4SzRadE',
    appId: '1:309848691890:web:6f48cda77a6ca6aabae5ab',
    messagingSenderId: '309848691890',
    projectId: 'fir-xflutterxauth-1b024',
    authDomain: 'fir-xflutterxauth-1b024.firebaseapp.com',
    storageBucket: 'fir-xflutterxauth-1b024.firebasestorage.app',
    measurementId: 'G-Q94S8G8WHJ',
  );
}
